-- V17__webhook.sql: Webhook 注册与事件推送机制
-- 覆盖 1 个 JPA 实体表 (WebhookEntity)
-- 列名与 Hibernate SpringPhysicalNamingStrategy 生成结果一致（下划线命名）

-- ===== Webhook 表 (WebhookEntity) =====
CREATE TABLE IF NOT EXISTS webhooks (
    -- 标准 IDENTITY：原 AUTO_INCREMENT 是 MySQL 方言，PostgreSQL 建表直接语法错误
    -- （H2 两版语法都认，所以此前只有 PG 通路会炸）；与 V9__license_table.sql 一致
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url VARCHAR(500) NOT NULL,
    secret VARCHAR(200),
    events VARCHAR(500),
    tenant_id INTEGER,
    enabled BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);