-- V18__flight_log_table.sql: FlightLog 持久化表
-- 覆盖 1 个 JPA 实体表 (FlightLogEntity)
-- 列名与 Hibernate SpringPhysicalNamingStrategy 生成结果一致（下划线命名）

-- ===== flight_log 表 (FlightLogEntity) =====
CREATE TABLE IF NOT EXISTS flight_log (
    -- 标准 IDENTITY：原 AUTO_INCREMENT 是 MySQL 方言，PostgreSQL 建表直接语法错误
    -- （H2 两版语法都认，所以此前只有 PG 通路会炸）；与 V9__license_table.sql 一致
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMP,
    type VARCHAR(50),
    sysid INTEGER,
    -- 裸 DOUBLE 同样是 MySQL/H2 方言，PostgreSQL 报 type "double" does not exist
    -- （Pass C 实测在 V13 复现），统一 DOUBLE PRECISION（同 V1 写法）
    lat DOUBLE PRECISION,
    lon DOUBLE PRECISION,
    relative_alt DOUBLE PRECISION,
    groundspeed DOUBLE PRECISION,
    battery INTEGER,
    voltage INTEGER,
    mode VARCHAR(50),
    armed BOOLEAN,
    online BOOLEAN,
    severity INTEGER,
    text VARCHAR(2000),
    tenant_id INTEGER
);

-- ===== 索引 =====
CREATE INDEX IF NOT EXISTS idx_flight_log_type_sysid ON flight_log (type, sysid);
CREATE INDEX IF NOT EXISTS idx_flight_log_timestamp ON flight_log (timestamp);
CREATE INDEX IF NOT EXISTS idx_flight_log_tenant_id ON flight_log (tenant_id);