-- V21__audit_log_table.sql: 审计日志持久化表（含哈希链）
-- 覆盖 1 个 JPA 实体表 (AuditLogEntity)
-- 列名与 Hibernate SpringPhysicalNamingStrategy 生成结果一致（下划线命名）
--
-- 哈希链：每行的 entry_hash = SHA-256(prev_hash + 字段规范串)，
-- 首行 prev_hash 为 64 个 0（创世）。任何对历史行的篡改都会在
-- GET /api/v1/audit/verify 的链校验中暴露（见 AuditService.verifyChain）。
-- 列名用 entry_hash 而非 hash：hash 在部分数据库里是保留字/函数名。

CREATE TABLE IF NOT EXISTS audit_log (
    -- 标准 IDENTITY（同 V9/V18，PostgreSQL 与 H2 两方言兼容）
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMP,
    user_id VARCHAR(255),
    action VARCHAR(20),
    target VARCHAR(512),
    detail VARCHAR(2000),
    ip VARCHAR(64),
    prev_hash VARCHAR(64),
    entry_hash VARCHAR(64)
);

-- ===== 索引 =====
CREATE INDEX IF NOT EXISTS idx_audit_log_timestamp ON audit_log (timestamp);
CREATE INDEX IF NOT EXISTS idx_audit_log_user_id ON audit_log (user_id);
