-- V23__dock_tables.sql: F2 机巢管控——机巢、状态日志、定时任务、运行记录、日结度量
-- 依赖 C4 持久化口径：主数据落 PG（H2 兼容语法，与既有迁移同风格）

CREATE TABLE IF NOT EXISTS docks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(50),
    name VARCHAR(100) NOT NULL,
    model VARCHAR(100),
    sn VARCHAR(100) NOT NULL UNIQUE,
    lat DOUBLE PRECISION,
    lon DOUBLE PRECISION,
    state VARCHAR(20) NOT NULL DEFAULT 'OFFLINE',
    temperature_c DOUBLE PRECISION,
    battery_pct INTEGER,
    drone_sysid INTEGER,
    last_heartbeat_ms BIGINT NOT NULL DEFAULT 0,
    temp_warn_c DOUBLE PRECISION NOT NULL DEFAULT 55,
    temp_crit_c DOUBLE PRECISION NOT NULL DEFAULT 70,
    reboot_until_ms BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS dock_state_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dock_id BIGINT NOT NULL,
    from_state VARCHAR(20),
    to_state VARCHAR(20) NOT NULL,
    reason VARCHAR(200),
    ts BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_dock_state_log_dock_ts ON dock_state_log (dock_id, ts);

CREATE TABLE IF NOT EXISTS dock_schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dock_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    cron_expr VARCHAR(60) NOT NULL,
    waypoints TEXT,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    last_run_at BIGINT,
    last_result VARCHAR(30),
    next_due_ms BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_dock_schedules_dock ON dock_schedules (dock_id);

CREATE TABLE IF NOT EXISTS dock_run_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schedule_id BIGINT NOT NULL,
    dock_id BIGINT NOT NULL,
    started_at BIGINT NOT NULL,
    finished_at BIGINT,
    result VARCHAR(20) NOT NULL,
    reason VARCHAR(200),
    flight_minutes DOUBLE PRECISION
);
CREATE INDEX IF NOT EXISTS idx_dock_run_log_dock_ts ON dock_run_log (dock_id, started_at);

CREATE TABLE IF NOT EXISTS dock_metrics_daily (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dock_id BIGINT NOT NULL,
    day_date VARCHAR(10) NOT NULL,
    sorties INTEGER NOT NULL DEFAULT 0,
    flight_minutes DOUBLE PRECISION NOT NULL DEFAULT 0,
    door_cycles INTEGER NOT NULL DEFAULT 0,
    online_seconds BIGINT NOT NULL DEFAULT 0,
    fault_count INTEGER NOT NULL DEFAULT 0,
    temp_excursions INTEGER NOT NULL DEFAULT 0,
    battery_swaps INTEGER NOT NULL DEFAULT 0,
    avg_charge_time_min DOUBLE PRECISION,
    CONSTRAINT uk_dock_metrics_day UNIQUE (dock_id, day_date)
);
