-- V24__defect_workorder_tables.sql: F4 缺陷报告与工单闭环
-- 缺陷（从 F1 拍照结果晋升或人工立案）+ 工单（状态机 + 复检闭环）

CREATE TABLE IF NOT EXISTS defects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(50),
    kind VARCHAR(40) NOT NULL,
    confidence DOUBLE PRECISION NOT NULL DEFAULT 0,
    lat DOUBLE PRECISION NOT NULL,
    lon DOUBLE PRECISION NOT NULL,
    severity VARCHAR(4) NOT NULL DEFAULT 'P2',
    status VARCHAR(12) NOT NULL DEFAULT 'OPEN',
    source VARCHAR(20) NOT NULL DEFAULT 'manual',
    note VARCHAR(500),
    last_seen_at BIGINT,
    created_at BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_defects_status ON defects (status);
CREATE INDEX IF NOT EXISTS idx_defects_created ON defects (created_at);

CREATE TABLE IF NOT EXISTS work_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(50),
    title VARCHAR(200) NOT NULL,
    note VARCHAR(1000),
    status VARCHAR(12) NOT NULL DEFAULT 'OPEN',
    cancel_reason VARCHAR(300),
    verified_at BIGINT,
    verified_detail VARCHAR(500),
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_work_orders_status ON work_orders (status);

CREATE TABLE IF NOT EXISTS work_order_defects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_order_id BIGINT NOT NULL,
    defect_id BIGINT NOT NULL,
    CONSTRAINT uk_wo_defect UNIQUE (work_order_id, defect_id)
);
