-- V2__orch_tables.sql: 编排模块三张核心表
-- 覆盖 3 个 JPA 实体表
-- 列名与 Hibernate SpringPhysicalNamingStrategy 生成结果一致

-- ===== 编排计划表 (OrchestrationPlanEntity) =====
CREATE TABLE IF NOT EXISTS orch_plan (
    plan_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    status VARCHAR(20) NOT NULL,
    resource_pool TEXT NOT NULL,
    create_time BIGINT,
    start_time BIGINT,
    end_time BIGINT
);

-- ===== 任务步骤表 (TaskStepEntity) =====
CREATE TABLE IF NOT EXISTS orch_step (
    step_id VARCHAR(50) PRIMARY KEY,
    plan_id BIGINT NOT NULL,
    module VARCHAR(20) NOT NULL,
    action VARCHAR(30) NOT NULL,
    params TEXT,
    depends_on TEXT,
    status VARCHAR(20) NOT NULL,
    required_resources TEXT,
    timeout_ms BIGINT,
    continue_on_failure BOOLEAN,
    start_time BIGINT,
    end_time BIGINT,
    fail_reason VARCHAR(500),
    module_task_id VARCHAR(100)
);

-- ===== 条件触发器表 (ConditionTriggerEntity) =====
CREATE TABLE IF NOT EXISTS orch_trigger (
    trigger_id VARCHAR(50) PRIMARY KEY,
    plan_id BIGINT NOT NULL,
    type VARCHAR(20) NOT NULL,
    condition TEXT,
    action VARCHAR(20) NOT NULL,
    target_plan_id BIGINT
);