-- V2__orch_tables.sql: 编排模块三张核心表
-- 覆盖 3 个 JPA 实体表
-- 列名与 Hibernate SpringPhysicalNamingStrategy 生成结果一致
-- 漂移修正（2026-09-30，prod profile + PG 的 Hibernate ddl-auto=validate 实测）：
--   orch_plan.pause_reason、orch_step.id / uk_plan_step、orch_trigger.id / uk_plan_trigger
--   此前缺失，导致 Pass C 报 Schema-validation: missing column。

-- ===== 编排计划表 (OrchestrationPlanEntity) =====
CREATE TABLE IF NOT EXISTS orch_plan (
    plan_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    status VARCHAR(20) NOT NULL,
    resource_pool TEXT NOT NULL,
    create_time BIGINT,
    start_time BIGINT,
    end_time BIGINT,
    -- PauseReason 枚举名（EMERGENCY / MANUAL），对齐 OrchestrationPlanEntity.pauseReason
    pause_reason VARCHAR(255)
);

-- ===== 任务步骤表 (TaskStepEntity) =====
CREATE TABLE IF NOT EXISTS orch_step (
    -- 标准 IDENTITY 代理主键；业务标识 step_id 非唯一（同一计划内唯一，见 uk_plan_step）
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    step_id VARCHAR(50),
    plan_id BIGINT NOT NULL,
    module VARCHAR(20) NOT NULL,
    action VARCHAR(30) NOT NULL,
    params TEXT,
    depends_on TEXT,
    status VARCHAR(20) NOT NULL,
    required_resources TEXT,
    timeout_ms BIGINT,
    continue_on_failure BOOLEAN,
    start_time BIGINT,
    end_time BIGINT,
    fail_reason VARCHAR(500),
    module_task_id VARCHAR(100),
    CONSTRAINT uk_plan_step UNIQUE (plan_id, step_id)
);

-- ===== 条件触发器表 (ConditionTriggerEntity) =====
CREATE TABLE IF NOT EXISTS orch_trigger (
    -- 同 orch_step：IDENTITY 代理主键 + 计划内业务唯一键
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trigger_id VARCHAR(50),
    plan_id BIGINT NOT NULL,
    type VARCHAR(20) NOT NULL,
    condition TEXT,
    action VARCHAR(20) NOT NULL,
    target_plan_id BIGINT,
    CONSTRAINT uk_plan_trigger UNIQUE (plan_id, trigger_id)
);