-- V6__user_tenant_tables.sql: 用户与租户模块两张表
-- 覆盖 2 个 JPA 实体表 (TenantEntity, UserEntity)
-- 列名与 Hibernate SpringPhysicalNamingStrategy 生成结果一致

-- ===== 租户表 (TenantEntity) =====
CREATE TABLE IF NOT EXISTS tenant (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    code VARCHAR(50) NOT NULL UNIQUE,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ===== 用户表 (UserEntity) =====
CREATE TABLE IF NOT EXISTS app_user (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password_hash VARCHAR(100) NOT NULL,
    role VARCHAR(20) NOT NULL,
    tenant_id INTEGER,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 默认租户和管理员用户（密码: admin 的 BCrypt 哈希）
INSERT INTO tenant (name, code, enabled) VALUES ('Default', 'default', true);
INSERT INTO app_user (username, password_hash, role, tenant_id, enabled)
VALUES ('admin', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'ADMIN', 1, true);