-- V9__license_table.sql: License 授权表
-- 存储 License 信息，支持模块授权、API 调用限制、并发无人机限制等扩展字段

CREATE TABLE IF NOT EXISTS license (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    license_id VARCHAR(100) NOT NULL UNIQUE,
    tenant_id VARCHAR(50) NOT NULL,
    product_name VARCHAR(100) NOT NULL,
    max_devices INTEGER NOT NULL DEFAULT 0,
    modules VARCHAR(255),
    max_api_calls_per_day INTEGER NOT NULL DEFAULT 0,
    max_concurrent_drones INTEGER NOT NULL DEFAULT 0,
    expiry_date TIMESTAMP,
    issued_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    issued_to VARCHAR(100),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    signature VARCHAR(2048),
    signer_cert VARCHAR(4096),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 索引：按租户查询 License
CREATE INDEX IF NOT EXISTS idx_license_tenant_id ON license (tenant_id);
-- 索引：按 license_id 查询
CREATE INDEX IF NOT EXISTS idx_license_license_id ON license (license_id);