package io.aerofleet.mavlink.messages;

import io.aerofleet.mavlink.MavlinkFrame;
import io.aerofleet.mavlink.PayloadCodec;

import java.nio.ByteBuffer;

/**
 * RADIO_STATUS (msgId=109, LEN=9, min 9, CRC=175). Status generated by a
 * radio and injected into the MAVLink stream. SiK convention: RSSI/noise
 * units are device-dependent, approx 2x dB (i.e. raw = ~2 * dB value);
 * UINT8_MAX (255) marks invalid/unknown.
 *
 * Offsets: rssi@0, remrssi@1, txbuf@2, noise@3, remnoise@4,
 * rxerrors@5, fixed@7.
 */
public final class RadioStatus extends MavlinkMessage {

    public static final int ID = 109;
    public static final int LEN = 9;
    public static final int INVALID = 255;

    public final int rssi;
    public final int remrssi;
    /** Remaining free transmitter buffer space [%]. */
    public final int txbuf;
    public final int noise;
    public final int remnoise;
    /** Radio packet receive errors since boot. */
    public final int rxerrors;
    /** Error-corrected radio packets since boot. */
    public final int fixed;

    public RadioStatus(int rssi, int remrssi, int txbuf,
                       int noise, int remnoise, int rxerrors, int fixed) {
        this.rssi = rssi;
        this.remrssi = remrssi;
        this.txbuf = txbuf;
        this.noise = noise;
        this.remnoise = remnoise;
        this.rxerrors = rxerrors;
        this.fixed = fixed;
    }

    @Override
    public int messageId() {
        return ID;
    }

    @Override
    public byte[] encode() {
        byte[] buf = PayloadCodec.alloc(LEN);
        PayloadCodec.putU8(buf, 0, rssi);
        PayloadCodec.putU8(buf, 1, remrssi);
        PayloadCodec.putU8(buf, 2, txbuf);
        PayloadCodec.putU8(buf, 3, noise);
        PayloadCodec.putU8(buf, 4, remnoise);
        PayloadCodec.putU16(buf, 5, rxerrors);
        PayloadCodec.putU16(buf, 7, fixed);
        return buf;
    }

    public static RadioStatus decode(MavlinkFrame f) {
        ByteBuffer b = le(f.getPayload());
        int len = f.getPayloadLength();
        return new RadioStatus(
                PayloadCodec.u8(b, 0),
                PayloadCodec.u8(b, 1),
                PayloadCodec.u8(b, 2),
                PayloadCodec.u8(b, 3),
                PayloadCodec.u8(b, 4),
                len > 6 ? PayloadCodec.u16(b, 5) : 0,
                len > 8 ? PayloadCodec.u16(b, 7) : 0);
    }
}
