package io.aerofleet.cloud.flightlog;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

import java.time.Instant;
import java.util.HashMap;
import java.util.Map;

/**
 * FlightLog JPA 实体，映射 flight_log 表。
 * <p>
 * 用于将飞行日志事件（telemetry/alert/mission/connectivity）持久化到 PostgreSQL，
 * 替代或补充现有的 JSONL 文件路径。字段名遵循 camelCase，Hibernate
 * SpringPhysicalNamingStrategy 自动转换为下划线列名（如 relativeAlt → relative_alt）。
 */
@Entity
@Table(name = "flight_log")
public class FlightLogEntity {

    /**
     * 主键由数据库生成（V18 的 {@code GENERATED BY DEFAULT AS IDENTITY}）。
     * <p>
     * 曾试过改成 {@code GenerationType.SEQUENCE} 以启用 Hibernate insert 批处理，实测在
     * prod 档启动失败：{@code ddl-auto=validate} 会走
     * {@code AbstractSchemaValidator.validateSequence}，而序列明明存在
     * （{@code pg_class} 查到 {@code public.flight_log_id_seq}、Flyway 历史里 V22 success）
     * 它仍报 {@code Schema-validation: missing sequence}。所以放弃"让 Hibernate 批"，
     * 改为在写队列里用显式 JDBC 批量插入（见 {@code FlightLogService}）——
     * 批处理照样成立，且不再依赖驱动的序列元数据解析。
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Long id;

    @Column(name = "timestamp")
    private Instant timestamp;

    @Column(name = "type")
    private String type;

    @Column(name = "sysid")
    private int sysid;

    @Column(name = "lat")
    private Double lat;

    @Column(name = "lon")
    private Double lon;

    @Column(name = "relative_alt")
    private Double relativeAlt;

    @Column(name = "groundspeed")
    private Double groundspeed;

    @Column(name = "battery")
    private Integer battery;

    @Column(name = "voltage")
    private Integer voltage;

    @Column(name = "mode")
    private String mode;

    @Column(name = "armed")
    private Boolean armed;

    @Column(name = "online")
    private Boolean online;

    @Column(name = "severity")
    private Integer severity;

    @Column(name = "text")
    private String text;

    @Column(name = "tenant_id")
    private Integer tenantId;

    /** JPA 要求的无参构造器 */
    public FlightLogEntity() {
    }

    /** 全参构造器 */
    public FlightLogEntity(Long id, Instant timestamp, String type, int sysid,
                           Double lat, Double lon, Double relativeAlt, Double groundspeed,
                           Integer battery, Integer voltage, String mode, Boolean armed,
                           Boolean online, Integer severity, String text, Integer tenantId) {
        this.id = id;
        this.timestamp = timestamp;
        this.type = type;
        this.sysid = sysid;
        this.lat = lat;
        this.lon = lon;
        this.relativeAlt = relativeAlt;
        this.groundspeed = groundspeed;
        this.battery = battery;
        this.voltage = voltage;
        this.mode = mode;
        this.armed = armed;
        this.online = online;
        this.severity = severity;
        this.text = text;
        this.tenantId = tenantId;
    }

    /**
     * 从事件 Map 构造 FlightLogEntity（工厂方法）。
     * <p>
     * Map 的 key 名与 JSONL 路径一致：t/type/sysid/lat/lon/relativeAlt/groundspeed/
     * battery/voltage/mode/armed/online/severity/text。
     *
     * @param event 事件 Map
     * @return FlightLogEntity 实例
     */
    @SuppressWarnings("unchecked")
    public static FlightLogEntity from(Map<String, Object> event) {
        FlightLogEntity e = new FlightLogEntity();
        e.type = (String) event.get("type");
        e.sysid = event.get("sysid") instanceof Number n ? n.intValue() : 0;
        e.lat = event.get("lat") instanceof Number n ? n.doubleValue() : null;
        e.lon = event.get("lon") instanceof Number n ? n.doubleValue() : null;
        e.relativeAlt = event.get("relativeAlt") instanceof Number n ? n.doubleValue() : null;
        e.groundspeed = event.get("groundspeed") instanceof Number n ? n.doubleValue() : null;
        e.battery = event.get("battery") instanceof Number n ? n.intValue() : null;
        e.voltage = event.get("voltage") instanceof Number n ? n.intValue() : null;
        e.mode = (String) event.get("mode");
        e.armed = event.get("armed") instanceof Boolean b ? b : null;
        e.online = event.get("online") instanceof Boolean b ? b : null;
        e.severity = event.get("severity") instanceof Number n ? n.intValue() : null;
        e.text = (String) event.get("text");
        e.tenantId = event.get("tenantId") instanceof Number n ? n.intValue() : null;

        // timestamp: 优先用 Map 中的 "t" 字段（ISO LocalDateTime 字符串），否则用当前时间
        Object t = event.get("t");
        if (t instanceof String s) {
            try {
                e.timestamp = java.time.LocalDateTime.parse(s,
                        java.time.format.DateTimeFormatter.ISO_LOCAL_DATE_TIME)
                        .atZone(java.time.ZoneId.systemDefault())
                        .toInstant();
            } catch (Exception ex) {
                e.timestamp = Instant.now();
            }
        } else {
            e.timestamp = Instant.now();
        }

        return e;
    }

    /**
     * 将 Entity 转换为 Map（用于 query() 返回格式兼容 JSONL 路径）。
     * <p>
     * 返回的 Map key 名与 JSONL 路径一致：t/type/sysid/lat/lon/relativeAlt/groundspeed/
     * battery/voltage/mode/armed/online/severity/text。
     *
     * @return Map<String, Object>
     */
    public Map<String, Object> toMap() {
        Map<String, Object> m = new HashMap<>();
        m.put("t", timestamp != null
                ? timestamp.atZone(java.time.ZoneId.systemDefault())
                        .toLocalDateTime()
                        .format(java.time.format.DateTimeFormatter.ISO_LOCAL_DATE_TIME)
                : null);
        m.put("type", type);
        m.put("sysid", sysid);
        m.put("lat", lat);
        m.put("lon", lon);
        m.put("relativeAlt", relativeAlt);
        m.put("groundspeed", groundspeed);
        m.put("battery", battery);
        m.put("voltage", voltage);
        m.put("mode", mode);
        m.put("armed", armed);
        m.put("online", online);
        m.put("severity", severity);
        m.put("text", text);
        return m;
    }

    // --- getters / setters ---

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Instant getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(Instant timestamp) {
        this.timestamp = timestamp;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public int getSysid() {
        return sysid;
    }

    public void setSysid(int sysid) {
        this.sysid = sysid;
    }

    public Double getLat() {
        return lat;
    }

    public void setLat(Double lat) {
        this.lat = lat;
    }

    public Double getLon() {
        return lon;
    }

    public void setLon(Double lon) {
        this.lon = lon;
    }

    public Double getRelativeAlt() {
        return relativeAlt;
    }

    public void setRelativeAlt(Double relativeAlt) {
        this.relativeAlt = relativeAlt;
    }

    public Double getGroundspeed() {
        return groundspeed;
    }

    public void setGroundspeed(Double groundspeed) {
        this.groundspeed = groundspeed;
    }

    public Integer getBattery() {
        return battery;
    }

    public void setBattery(Integer battery) {
        this.battery = battery;
    }

    public Integer getVoltage() {
        return voltage;
    }

    public void setVoltage(Integer voltage) {
        this.voltage = voltage;
    }

    public String getMode() {
        return mode;
    }

    public void setMode(String mode) {
        this.mode = mode;
    }

    public Boolean getArmed() {
        return armed;
    }

    public void setArmed(Boolean armed) {
        this.armed = armed;
    }

    public Boolean getOnline() {
        return online;
    }

    public void setOnline(Boolean online) {
        this.online = online;
    }

    public Integer getSeverity() {
        return severity;
    }

    public void setSeverity(Integer severity) {
        this.severity = severity;
    }

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

    public Integer getTenantId() {
        return tenantId;
    }

    public void setTenantId(Integer tenantId) {
        this.tenantId = tenantId;
    }

    // ===== 批量插入的列/值同源导出（显式 JDBC 批处理用） =====

    /**
     * 参与插入的字段，按声明顺序反射得到（排除主键与静态字段）。
     * <p>
     * 列名与占位符值都从这同一份列表派生，所以即使 JVM 不保证 getDeclaredFields 的顺序，
     * 列与值也不可能错位——这是"手写 INSERT 列清单迟早漂移"的替代品。
     */
    private static final java.util.List<java.lang.reflect.Field> INSERT_FIELDS = resolveInsertFields();

    private static java.util.List<java.lang.reflect.Field> resolveInsertFields() {
        java.util.List<java.lang.reflect.Field> out = new java.util.ArrayList<>();
        for (java.lang.reflect.Field f : FlightLogEntity.class.getDeclaredFields()) {
            jakarta.persistence.Column c = f.getAnnotation(jakarta.persistence.Column.class);
            if (c == null || f.isAnnotationPresent(jakarta.persistence.Id.class)
                    || java.lang.reflect.Modifier.isStatic(f.getModifiers())) {
                continue;
            }
            f.setAccessible(true);
            out.add(f);
        }
        return java.util.List.copyOf(out);
    }

    /** 插入列名（顺序与 {@link #insertValues} 严格对应）。 */
    public static String[] insertColumnNames() {
        String[] names = new String[INSERT_FIELDS.size()];
        for (int i = 0; i < names.length; i++) {
            names[i] = INSERT_FIELDS.get(i).getAnnotation(jakarta.persistence.Column.class).name();
        }
        return names;
    }

    /**
     * 每列的 java.sql.Types，供 null 值显式 setNull 使用
     * （{@code setObject(i, null)} 在 PostgreSQL 驱动上会因无法推断类型而报错）。
     */
    public static int[] insertSqlTypes() {
        int[] types = new int[INSERT_FIELDS.size()];
        for (int i = 0; i < types.length; i++) {
            Class<?> t = INSERT_FIELDS.get(i).getType();
            if (t == java.time.Instant.class) {
                types[i] = java.sql.Types.TIMESTAMP;
            } else if (t == String.class) {
                types[i] = java.sql.Types.VARCHAR;
            } else if (t == Integer.class || t == int.class) {
                types[i] = java.sql.Types.INTEGER;
            } else if (t == Long.class || t == long.class) {
                types[i] = java.sql.Types.BIGINT;
            } else if (t == Double.class || t == double.class) {
                types[i] = java.sql.Types.DOUBLE;
            } else if (t == Boolean.class || t == boolean.class) {
                types[i] = java.sql.Types.BOOLEAN;
            } else {
                types[i] = java.sql.Types.OTHER;
            }
        }
        return types;
    }

    /** 取本实体各列的值（{@code Instant} 转 {@link java.sql.Timestamp}，驱动兼容）。 */
    public static Object[] insertValues(FlightLogEntity entity) {
        Object[] values = new Object[INSERT_FIELDS.size()];
        for (int i = 0; i < values.length; i++) {
            try {
                Object v = INSERT_FIELDS.get(i).get(entity);
                values[i] = v instanceof java.time.Instant ts ? java.sql.Timestamp.from(ts) : v;
            } catch (IllegalAccessException e) {
                throw new IllegalStateException("无法读取 " + INSERT_FIELDS.get(i).getName(), e);
            }
        }
        return values;
    }
}
